# Generated by scripts/generate_users.py -- do not edit by hand.
# Source: groups/uio/users/iti-ops.json

provider "aws" {
  alias = "uio_iti_ops"

  region     = var.region
  access_key = jsondecode(data.http.user_creds["uio/iti-ops"].response_body)[0].accessKey
  secret_key = jsondecode(data.http.user_creds["uio/iti-ops"].response_body)[0].secretKey

  # Cloudian speaks the S3 and IAM APIs but none of the AWS metadata services.
  s3_use_path_style           = true
  skip_credentials_validation = true
  skip_region_validation      = true
  skip_requesting_account_id  = true
  skip_metadata_api_check     = true

  endpoints {
    s3  = var.s3_endpoint
    iam = var.iam_endpoint
  }
}

module "uio_iti_ops" {
  source = "./modules/cloudian-user"

  spec                = local.users["uio/iti-ops"]
  manage_iam_users    = var.manage_iam_users
  manage_iam_policies = var.manage_iam_policies

  providers = {
    aws = aws.uio_iti_ops
  }
}
