# Generated by scripts/generate_users.py -- do not edit by hand.
# Source: groups/ffu/users/ffu-dht.json

provider "aws" {
  alias = "ffu_ffu_dht"

  region     = var.region
  access_key = jsondecode(data.http.user_creds["ffu/ffu-dht"].response_body)[0].accessKey
  secret_key = jsondecode(data.http.user_creds["ffu/ffu-dht"].response_body)[0].secretKey

  # Cloudian speaks the S3 and IAM APIs but none of the AWS metadata services.
  s3_use_path_style           = true
  skip_credentials_validation = true
  skip_region_validation      = true
  skip_requesting_account_id  = true
  skip_metadata_api_check     = true

  endpoints {
    s3  = var.s3_endpoint
    iam = var.iam_endpoint
  }
}

module "ffu_ffu_dht" {
  source = "./modules/cloudian-user"

  spec                = local.users["ffu/ffu-dht"]
  manage_iam_users    = var.manage_iam_users
  manage_iam_policies = var.manage_iam_policies

  providers = {
    aws = aws.ffu_ffu_dht
  }
}
