# Generated by scripts/generate_users.py -- do not edit by hand.

output "buckets" {
  value = {
    "ffu/ffu-dht" = module.ffu_ffu_dht.buckets
    "uio/iti-ops" = module.uio_iti_ops.buckets
  }
}

output "iam_users" {
  value = {
    "ffu/ffu-dht" = module.ffu_ffu_dht.iam_users
    "uio/iti-ops" = module.uio_iti_ops.iam_users
  }
}

output "iam_access_keys" {
  sensitive = true
  value = {
    "ffu/ffu-dht" = module.ffu_ffu_dht.iam_access_keys
    "uio/iti-ops" = module.uio_iti_ops.iam_access_keys
  }
}
