#!/usr/bin/env python3
"""Generate the per-user Terraform stubs from the groups/ JSON tree.

Terraform provider blocks cannot be created with for_each, and every Cloudian
user owns its buckets under its own S3 credentials. So each user needs one
`provider "aws"` alias of its own. That boilerplate is generated here; the
hand-edited content lives entirely in groups/<group>/users/<user>.json.

Each stub points its provider at the per-user credentials that data.http
"user_creds" in providers.tf resolves at plan time, from the cluster's Admin
API. Stubs are written to the repository root as user_<alias>.tf, because
Terraform only loads .tf files from the root module directory and does not
recurse.

Run after adding, renaming or removing a user file:

    make generate
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GROUPS_DIR = ROOT / "groups"

PREFIX = "user_"
OUTPUTS_FILE = "zz_generated_outputs.tf"
BANNER = "# Generated by scripts/generate_users.py -- do not edit by hand.\n"

STUB = """{banner}# Source: groups/{group}/users/{user}.json

provider "aws" {{
  alias = "{alias}"

  region     = var.region
  access_key = jsondecode(data.http.user_creds["{key}"].response_body)[0].accessKey
  secret_key = jsondecode(data.http.user_creds["{key}"].response_body)[0].secretKey

  # Cloudian speaks the S3 and IAM APIs but none of the AWS metadata services.
  s3_use_path_style           = true
  skip_credentials_validation = true
  skip_region_validation      = true
  skip_requesting_account_id  = true
  skip_metadata_api_check     = true

  endpoints {{
    s3  = var.s3_endpoint
    iam = var.iam_endpoint
  }}
}}

module "{alias}" {{
  source = "./modules/cloudian-user"

  spec                = local.users["{key}"]
  manage_iam_users    = var.manage_iam_users
  manage_iam_policies = var.manage_iam_policies

  providers = {{
    aws = aws.{alias}
  }}
}}
"""


def to_alias(group: str, user: str) -> str:
    """Turn "uio" / "iti-ops" into a valid Terraform identifier."""
    alias = re.sub(r"[^A-Za-z0-9_]", "_", f"{group}_{user}")
    if not re.match(r"[A-Za-z_]", alias):
        alias = f"u_{alias}"
    return alias


def discover() -> list[dict]:
    if not GROUPS_DIR.is_dir():
        sys.exit(f"error: {GROUPS_DIR} does not exist")

    entries = []
    for path in sorted(GROUPS_DIR.glob("*/users/*.json")):
        group = path.parent.parent.name
        user = path.stem

        try:
            json.loads(path.read_text())
        except json.JSONDecodeError as exc:
            sys.exit(f"error: {path.relative_to(ROOT)} is not valid JSON: {exc}")

        entries.append(
            {
                "group": group,
                "user": user,
                "key": f"{group}/{user}",
                "alias": to_alias(group, user),
            }
        )

    seen: dict[str, str] = {}
    for e in entries:
        if e["alias"] in seen:
            sys.exit(
                f"error: {e['key']} and {seen[e['alias']]} both map to the "
                f"Terraform alias '{e['alias']}'. Rename one of them."
            )
        seen[e["alias"]] = e["key"]

    return entries


def render_outputs(entries: list[dict]) -> str:
    def block(name: str, attr: str, sensitive: bool) -> str:
        lines = [f'output "{name}" {{']
        if sensitive:
            lines.append("  sensitive = true")
        lines.append("  value = {")
        for e in entries:
            lines.append(f'    "{e["key"]}" = module.{e["alias"]}.{attr}')
        lines.append("  }")
        lines.append("}")
        return "\n".join(lines)

    return "\n".join(
        [
            BANNER.rstrip("\n"),
            "",
            block("buckets", "buckets", False),
            "",
            block("iam_users", "iam_users", False),
            "",
            block("iam_access_keys", "iam_access_keys", True),
            "",
        ]
    )


def main() -> None:
    entries = discover()

    expected = set()
    for e in entries:
        filename = f"{PREFIX}{e['alias']}.tf"
        expected.add(filename)
        (ROOT / filename).write_text(STUB.format(banner=BANNER, **e))

    outputs_path = ROOT / OUTPUTS_FILE
    if entries:
        outputs_path.write_text(render_outputs(entries))
    else:
        outputs_path.unlink(missing_ok=True)

    # Drop stubs for users that no longer have a JSON file. Scoped to the
    # user_ prefix so hand-written root files are never touched.
    removed = []
    for stale in ROOT.glob(f"{PREFIX}*.tf"):
        if stale.name not in expected:
            stale.unlink()
            removed.append(stale.name)

    print(f"generated {len(entries)} user stub(s)")
    for name in sorted(removed):
        print(f"  removed stale {name}")


if __name__ == "__main__":
    main()
